### ISSUE TITLE
Is any way, we can pass the query or view name to get result set

### ISSUE THREAD

**Issue by safarigps** [DataBooster/DbWebApi#2]
Hi,

Just wondering, can we get result,if i can only pass view name instead of stored procedure name?

**Comment by AbelCheng** [comment]
No, query or view cannot be directly exposed as Web API, they have to be encapsulated into stored procedure or Oracle package. So that all the parameter metadata can be predetermined by database engine.

If your solution needs to use some dynamic queries, they also should be implemented in stored procedures.
