### ISSUE TITLE
Retrieving unnamed columns from a ResultSet

### ISSUE THREAD

**Issue by farrukhmpk** [DataBooster/DbWebApi#7]
Hi,

Great Project by the way.
I am having a bit of an issue, where I am trying to pass null to a mandatory SP parameter.
However, I am receiving Exception:

Value cannot be null. Parameter name: DynamicPropertyNameOfColumn0

Is there a solution to this problem? Please note I cannot change the Stored Proc.

**Comment by farrukhmpk** [comment]
Found out that by passing null, SP parameter is set to NULL.
However, my issue is with the returned result set where no column name is set by the stored procedure and it appears that column name/alias is mandatory.
Can you please help how can I by pass this issue?

**Comment by AbelCheng** [comment]
Sorry, I am not very clear about your issue. Could you explain it with an example or more context? Thanks

**Comment by farrukhmpk** [comment]
Hi Abel,
Apologies for the confusion, the issue is that we have a stored procedure that returns a ResultSet.
However, there are no Aliases on the column, i.e., the columns in the ResultSet do not have a "name".
When the project encounters such resultset, it throws the exception:

Value cannot be null. Parameter name: DynamicPropertyNameOfColumn0

Is there anyway to by pass this exception or the project allocates Aliases to columns by default?

**Comment by AbelCheng** [comment]
Oh, I see. Since each returned column is mapped to a unique property in DynamicObject, its name is required and must be unique in the result set.
Currently, there is no workaround if you cannot change/add the Stored Proc.

Let us have more deliberation, we can consider to automatically assign unique property names to those unnamed columns in the library implementation if need in practice.

(BTW, I updated the issue title to be more relevant.)

**Comment by AbelCheng** [comment]
A new release has just been published to NuGet, please update the package in your project. Then any unnamed column will be assigned an unique special name like '__UNNAMED__COLUMN__00001__'. Thanks
