### ISSUE TITLE
dbwebapi routing interfering with MVC routing.

### ISSUE THREAD

**Issue by McMead** [DataBooster/DbWebApi#8]
I want to use dbwebapi in my website but navigating a web page url results in an error saying the stored procedure does not exist.

**Comment by AbelCheng** [comment]
Actually the dbwebapi itself doesn't do anything about url routing. The routing should sit in website application level - before calling dbwebapi.

But the example websites provided in this repository were **trimmed** for webapi purpose only, you might find most of default modules/handlers have been removed from the example `web.config` file, and only route for webapi was added into the startup code.

So if you want to mix MVC web pages with webapi in the same website application, rather than using the example website as a frame to modify a lot, it could be easier to create a MVC web site from Visual Studio's template, let MVC page routing work first, then add dbwebapi package from NuGet. (the code of example websites act as reference only)

You can put your startup/config code of your website here for discussion if you don't mind potential disclosure of sensitive information.

**Comment by McMead** [comment]
Thank you, I was able to fix my problem by using attribute routing. Thanks again dbwebapi is a great resource.
